const ar=n=>n.toLocaleString('ar-SA');
const verses={
8:'اللَّهُ يَعْلَمُ مَا تَحْمِلُ كُلُّ أُنثَىٰ وَمَا تَغِيضُ الْأَرْحَامُ وَمَا تَزْدَادُ ۖ وَكُلُّ شَيْءٍ عِندَهُ بِمِقْدَارٍ',
9:'عَالِمُ الْغَيْبِ وَالشَّهَادَةِ الْكَبِيرُ الْمُتَعَالِ',
10:'سَوَاءٌ مِّنكُم مَّنْ أَسَرَّ الْقَوْلَ وَمَن جَهَرَ بِهِ وَمَنْ هُوَ مُسْتَخْفٍ بِاللَّيْلِ وَسَارِبٌ بِالنَّهَارِ',
11:'لَهُ مُعَقِّبَاتٌ مِّن بَيْنِ يَدَيْهِ وَمِنْ خَلْفِهِ يَحْفَظُونَهُ مِنْ أَمْرِ اللَّهِ ۗ إِنَّ اللَّهَ لَا يُغَيِّرُ مَا بِقَوْمٍ حَتَّىٰ يُغَيِّرُوا مَا بِأَنفُسِهِمْ ۗ وَإِذَا أَرَادَ اللَّهُ بِقَوْمٍ سُوءًا فَلَا مَرَدَّ لَهُ ۚ وَمَا لَهُم مِّن دُونِهِ مِن وَالٍ',
12:'هُوَ الَّذِي يُرِيكُمُ الْبَرْقَ خَوْفًا وَطَمَعًا وَيُنشِئُ السَّحَابَ الثِّقَالَ',
13:'وَيُسَبِّحُ الرَّعْدُ بِحَمْدِهِ وَالْمَلَائِكَةُ مِنْ خِيفَتِهِ وَيُرْسِلُ الصَّوَاعِقَ فَيُصِيبُ بِهَا مَن يَشَاءُ وَهُمْ يُجَادِلُونَ فِي اللَّهِ وَهُوَ شَدِيدُ الْمِحَالِ',
14:'لَهُ دَعْوَةُ الْحَقِّ ۖ وَالَّذِينَ يَدْعُونَ مِن دُونِهِ لَا يَسْتَجِيبُونَ لَهُم بِشَيْءٍ إِلَّا كَبَاسِطِ كَفَّيْهِ إِلَى الْمَاءِ لِيَبْلُغَ فَاهُ وَمَا هُوَ بِبَالِغِهِ ۚ وَمَا دُعَاءُ الْكَافِرِينَ إِلَّا فِي ضَلَالٍ',
15:'وَلِلَّهِ يَسْجُدُ مَن فِي السَّمَاوَاتِ وَالْأَرْضِ طَوْعًا وَكَرْهًا وَظِلَالُهُم بِالْغُدُوِّ وَالْآصَالِ'
};
const vocabulary=[['تَغِيضُ','تغيض','تنقص.'],['سَارِبٌ','سارب','سائر ظاهر في النهار.'],['مُعَقِّبَاتٌ','معقبات','ملائكة يتعاقبون في حفظ الإنسان بأمر الله.'],['خَوْفًا','خوفًا','خوفًا مما قد يصاحب البرق من الصواعق ونحوها.'],['طَمَعًا','طمعًا','رجاء نزول المطر ونفعه.'],['شَدِيدُ الْمِحَالِ','شديد المحال','شديد القوة والقدرة والأخذ.'],['دَعْوَةُ الْحَقِّ','دعوة الحق','إخلاص الدعاء والعبادة لله وحده.'],['بِالْغُدُوِّ','الغدو','أول النهار.'],['الْآصَالِ','الآصال','أواخر النهار.']];
const question=(text,options,answer)=>({text,options,answer});
const stages=[
{title:'علم الله الشامل',ids:[8],explanation:'يبين الله تعالى سعة علمه؛ فهو يعلم ما تحمله كل أنثى، وما تنقصه الأرحام وما تزداده. وكل شيء عنده مقدّر بحكمته وعلمه، فلا يزيد ولا ينقص إلا وفق تقديره.',questions:[question('ماذا تدل الآية على علم الله تعالى؟',['أن الله يعلم بعض الأشياء فقط.','أن الله يعلم ما يحدث للأرحام ويعلم كل شيء.','أن الإنسان يعلم الغيب.','أن الله يعلم الأشياء الظاهرة فقط.'],1)]},
{title:'الله يعلم السر والعلن',ids:[9,10,11],explanation:'الله عظيم، وعلمه محيط بالغيب والمشاهد، وبما نخفيه وما نعلنه في الليل والنهار. وله ملائكة يتعاقبون على حفظ الإنسان بأمره. لا يغيّر الله ما بقوم من نعمة حتى يغيّروا طاعتهم وشكرهم إلى معصية؛ وإذا رجعوا من المعصية إلى الطاعة غيّر حالهم إلى الخير. وإذا أراد بقوم عقوبة فلا أحد يردها أو يحميهم منه.',questions:[question('ماذا نتعلم من قوله تعالى: ﴿إِنَّ اللَّهَ لَا يُغَيِّرُ مَا بِقَوْمٍ حَتَّىٰ يُغَيِّرُوا مَا بِأَنفُسِهِمْ﴾؟',['أن الإنسان لا يستطيع تغيير نفسه.','أن علينا أن نسعى لإصلاح أنفسنا.','أن التغيير يحدث دون عمل.','أن الإنسان لا يحتاج إلى بذل أي جهد.'],1)]},
{title:'آيات الله في السماء',ids:[12,13],explanation:'من دلائل قدرة الله البرق؛ يخاف الناس ما يصاحبه من ضرر ويرجون المطر ونفعه. والله ينشئ السحاب الثقيل بالماء، والرعد يسبّح بحمده، والملائكة تسبّحه خوفًا منه. ويرسل الصواعق فيصيب بها من يشاء، وهو شديد القوة، لا يعجزه شيء؛ فهو وحده المستحق للعبادة.',questions:[question('لماذا يرى الناس البرق خوفًا وطمعًا؟',['خوفًا من الصواعق وطمعًا في المطر ونفعه.','خوفًا من الليل وطمعًا في النهار.','خوفًا من السحاب وطمعًا في البرق.','خوفًا من المطر وطمعًا في الصواعق.'],0),question('ما معنى ﴿شَدِيدُ الْمِحَالِ﴾؟',['شديد القوة والقدرة والأخذ.','شديد الضعف.','قليل القدرة.','كثير النوم.'],0)]},
{title:'دعوة الحق',ids:[14],explanation:'الدعاء والعبادة الحق لله وحده. أما المعبودات التي تُدعى من دونه فلا تستجيب ولا تنفع. ومثل من يدعوها كمثل عطشان يمد كفيه إلى ماء بعيد لا يصل إلى فمه؛ فلن يحصل على ما يريد. لذلك فدعاء غير الله باطل وضائع.',questions:[question('لمن تكون دعوة الحق؟',['لله وحده.','لأي مخلوق.','لجميع المعبودات.','للإنسان فقط.'],0)]},
{title:'خضوع الكون لله',ids:[15],explanation:'جميع من في السماوات والأرض خاضعون لله وتحت تدبيره؛ يسجد المؤمن طوعًا واختيارًا، ويخضع غيره لقهر الله وسلطانه. وحتى ظلال المخلوقات تسجد له في أول النهار وآخره؛ فلا يخرج شيء عن ملكه وتدبيره.',questions:[question('ماذا تبين الآية عن المخلوقات؟',['أنها مستقلة عن الله.','أنها خاضعة لله تعالى.','أن السجود خاص بالإنسان فقط.','أنها لا تخضع لأمر الله.'],1),question('أي كلمة تعني أول النهار؟',['الآصال.','الغدو.','معقبات.','سارب.'],1)]}
];
const goals=[['تقرير أن القرآن حق منزل من عند الله.','القرآن كلام الله، أخباره صادقة وهدايته تقود إلى الحق.'],['بيان كمال قدرة الله تعالى وعظيم سلطانه وحكمته وتدبيره.','نتأمل دلائل قدرته في خلقه، ونعلم أن الكون يجري بعلمه وتقديره.'],['تقرير البعث بعد الموت.','الله الذي خلق الخلق قادر على إحيائهم بعد موتهم للحساب والجزاء.'],['الاستدلال بتوحيد الربوبية على توحيد الألوهية وإخلاص العبادة لله.','لأن الله وحده الخالق والمدبر، فهو وحده المستحق للعبادة والدعاء.'],['بيان صفات السعداء وصفات الأشقياء.','السعادة في الإيمان والطاعة، والشقاء في الإعراض عن الحق والمعصية.']];
const summaries=[['علم الله الشامل بكل شيء.','﴿عَالِمُ الْغَيْبِ وَالشَّهَادَةِ﴾'],['كمال قدرة الله وعظيم سلطانه وحكمته وتدبيره.','﴿وَكُلُّ شَيْءٍ عِندَهُ بِمِقْدَارٍ﴾'],['دلائل قدرة الله في البرق والسحاب والصواعق.','﴿هُوَ الَّذِي يُرِيكُمُ الْبَرْقَ خَوْفًا وَطَمَعًا﴾'],['أهمية تغيير الإنسان لما في نفسه.','﴿إِنَّ اللَّهَ لَا يُغَيِّرُ مَا بِقَوْمٍ حَتَّىٰ يُغَيِّرُوا مَا بِأَنفُسِهِمْ﴾'],['توحيد الله وإخلاص العبادة له.','﴿لَهُ دَعْوَةُ الْحَقِّ﴾'],['خضوع الكون لله تعالى.','﴿وَلِلَّهِ يَسْجُدُ مَن فِي السَّمَاوَاتِ وَالْأَرْضِ﴾']];
const quiz=[question('أي موقف يدل على الإيمان بأن الله يعلم كل شيء؟',['أعتقد أن الله يعلم ما نخفيه وما نعلنه.','أعتقد أن الله يعلم الأشياء التي تظهر فقط.','أعتقد أن الإنسان يستطيع معرفة الغيب كله.','أعتقد أن الله لا يعلم ما يحدث في الليل.'],0),question('طالبة تريد أن تغيّر عادة سيئة لديها، ما التصرف الذي يناسب ما تعلمناه؟',['تنتظر أن تتغير العادة دون أن تفعل شيئًا.','تبدأ بمحاولة إصلاح نفسها وتغيير سلوكها.','تلقي المسؤولية على الآخرين.','تتوقف عن محاولة التغيير.'],1),question('رأت طالبة السحاب الثقيل، ثم سمعت الرعد. أي تأمّل يربط المشهد بمعاني الآيات؟',['السحاب يحمل المطر، والرعد يسبّح بحمد الله، وفيهما دليل على قدرته.','السحاب يملك إنزال المطر مستقلًا عن الله.','الرعد لا يدل على شيء من قدرة الله.','الظواهر في السماء خارجة عن تدبير الله.'],0),question('شُبّه دعاء غير الله بعطشان يمدّ كفيه إلى ماء لا يصل إليه. ما الفكرة التي يوضحها هذا المثل؟',['أن المعبودات من دون الله لا تستجيب، فيجب إخلاص الدعاء لله.','أن مجرد مدّ اليدين يغني عن الماء.','أن كل معبود قادر على إجابة الدعاء.','أن الماء يصل دائمًا إلى من يناديه.'],0),question('اختاري العبارة التي تلخص ما تعلمناه من الرحلة كلها:',['الله تعالى كامل العلم والقدرة، والعبادة له وحده، وجميع المخلوقات خاضعة له.','الإنسان يعلم كل شيء ويستطيع التحكم في الكون.','الظواهر الكونية تحدث بلا تقدير من الله.','يمكن توجيه العبادة والدعاء لأي مخلوق.'],0)];
const cards=[['توحيد الربوبية','الإيمان بأن الله وحده هو الخالق والمالك والمدبر.'],['توحيد الألوهية','إفراد الله تعالى بالعبادة.'],['إخلاص العبادة لله','أن تكون العبادة والدعاء لله وحده.']];
let page=0,unlocked=1,stageState=stages.map(s=>({at:0,solved:s.questions.map(()=>false),wrong:s.questions.map(()=>null)})),order=[2,0,1],sorted=false,sortMessage='',dragIndex=null,quizAt=-1,quizDone=false,quizSolved=quiz.map(()=>false),quizFirst=quiz.map(()=>null),quizWrong=quiz.map(()=>null);
const app=document.getElementById('app');
const navNames=['التعرّف على السورة','أهداف الرحلة',...stages.map(s=>s.title),'ماذا تعلمنا؟','الاختبار النهائي'];
const sourceLink=i=>`https://quran.ksu.edu.sa/tafseer/saadi/sura13-aya${i}.html`;
document.getElementById('sources').innerHTML=Object.keys(verses).map(i=>`<a href="${sourceLink(i)}" target="_blank" rel="noopener">الآية ${ar(+i)}</a>`).join('');
function verseMarkup(n){let t=verses[n];vocabulary.forEach(([word,label,meaning],i)=>{t=t.replace(word,`<button class="word" data-word="${i}" aria-label="معنى ${label}" aria-expanded="false">${word}</button>`)});return `<span class="ayah">${t}<span class="ayah-num">﴿${ar(n)}﴾</span></span>`;}
function actions(next,label='التالي',disabled=false){return `<div class="actions"><button class="secondary" data-go="${page-1}">السابق</button><button class="primary" data-next="${next}" ${disabled?'disabled':''}>${label}</button></div>`}
function disclosures(items){return items.map(([title,body])=>`<details class="disclosure"><summary>${title}</summary><p>${body}</p></details>`).join('')}
function questionMarkup(q,i,solved,wrong,final=false){return `<div class="question-panel" id="question"><span class="eyebrow">${final?'الاختبار النهائي':'تأمّلي وأجيبي'} · السؤال ${ar(i+1)} من ${ar(final?5:stages[page-3].questions.length)}</span><h2>${q.text}</h2><div class="options">${q.options.map((o,j)=>`<button class="option ${solved&&j===q.answer?'correct':wrong===j?'wrong':''}" data-answer="${j}" ${solved?'disabled':''}><span class="letter">${['أ','ب','ج','د'][j]}</span><span>${o}</span></button>`).join('')}</div><p class="feedback ${wrong!==null&&!solved?'error':''}" role="status">${solved?'أحسنتِ! ✨':wrong!==null?'حاولي مرة أخرى':''}</p>${final?`<button class="primary" data-quiz-next ${solved?'':'disabled'}>${i===4?'عرض النتيجة':'السؤال التالي'}</button>`:''}</div>`;}
function sortMarkup(){return `<section class="question-panel"><span class="eyebrow">نشاط تفاعلي</span><h2>رتّبي الفكرة</h2><p>رتبي البطاقات من الفكرة العامة إلى النتيجة التي نصل إليها.</p><p class="hint">اسحبي البطاقات من اليمين إلى اليسار، أو استخدمي «قدّمي» و«أخّري». على الشاشات الصغيرة يكون الترتيب من الأعلى إلى الأسفل.</p><div class="sort-list">${order.map((id,i)=>`<article class="sort-card" draggable="${!sorted}" data-sort="${i}"><span class="rank">الموضع ${ar(i+1)}</span><strong>${cards[id][0]}</strong><p>${cards[id][1]}</p><button class="move" data-move="${i},-1" ${i===0||sorted?'disabled':''} aria-label="قدمي بطاقة ${cards[id][0]}">قدّمي</button><button class="move" data-move="${i},1" ${i===2||sorted?'disabled':''} aria-label="أخري بطاقة ${cards[id][0]}">أخّري</button></article>`).join('')}</div><button class="secondary" data-check-sort ${sorted?'disabled':''}>تحققي من الترتيب</button><p role="status" class="feedback ${sortMessage&&!sorted?'error':''}">${sortMessage}</p></section>`;}
function render(focus=true){if(page===0){app.innerHTML=`<main class="hero" id="main" tabindex="-1"><div class="hero-inner"><span class="eyebrow">رحلة في العلم والقدرة والتوحيد</span><h1>رحلة مع آيات <span>سورة الرعد</span></h1><p class="verse-range">من الآية ٨ إلى الآية ١٥</p><p class="motto">«في كل آية دليل، وفي كل دليل معنى.»</p><button class="primary" data-go="1">ابدأ الرحلة</button><div class="hero-notes"><span>٥ مراحل للتأمّل</span><span>معانٍ تفاعلية</span><span>اختبار قصير</span></div></div></main>`;return;}
let content='';
if(page===1)content=`<span class="eyebrow">قبل أن نبدأ</span><h1>التعرّف على سورة الرعد</h1><p class="lede">مدخل إلى السورة التي نتأمل آياتها معًا.</p><section class="panel"><div class="facts"><div class="fact"><span>اسم السورة</span><strong>سورة الرعد</strong></div><div class="fact"><span>ترتيبها في المصحف</span><strong>١٣</strong></div><div class="fact"><span>عدد آياتها</span><strong>٤٣ آية</strong></div></div><h3>مكية أم مدنية؟</h3><p>اختلف العلماء في كونها مكية أو مدنية، وقيل مكية، وقيل مدنية.</p><h3>سبب التسمية</h3><p>سميت سورة الرعد لورود ذكر الرعد فيها.</p><h3>موضوع السورة</h3><p>بيان قدرة الله تعالى وعظمته، والاستدلال على وحدانيته، وذكر دلائل قدرته في الكون، وبيان موقف المؤمنين من الحق وموقف المكذبين منه.</p></section>${actions(2)}`;
if(page===2)content=`<span class="eyebrow">وجهتنا في هذه الرحلة</span><h1>أهداف الرحلة</h1><p class="lede">اضغطي على كل هدف لتتعرفي على معناه.</p>${disclosures(goals)}<p class="hint">هذه أهداف عامة في السورة، وتركّز رحلتنا في الآيات ٨–١٥ على علم الله وقدرته وتوحيده وخضوع الكون له.</p>${actions(3,'ابدأ رحلة الآيات')}`;
if(page>=3&&page<=7){let s=stages[page-3],state=stageState[page-3],all=state.solved.every(Boolean);content=`<span class="eyebrow">المرحلة ${ar(page-2)} من ٥ · ${s.ids.length===1?'الآية':'الآيات'} ${s.ids.map(ar).join('، ')}</span><h1>${s.title}</h1><div class="quran">${s.ids.map(verseMarkup).join(' ')}</div><div id="meaning" class="meaning" role="status"></div><p class="hint">اضغطي على الكلمات المميزة داخل الآيات لاكتشاف معناها.</p><section class="explain"><h2>نتأمّل المعنى</h2><p>${s.explanation}</p><a href="${sourceLink(s.ids[0])}" target="_blank" rel="noopener">تفسير السعدي · المصدر</a></section>${page===6?sortMarkup():''}${page!==6||sorted?questionMarkup(s.questions[state.at],state.at,state.solved[state.at],state.wrong[state.at]):'<p class="hint">أكملي الترتيب الصحيح ليظهر سؤال المرحلة.</p>'}${!all&&state.solved[state.at]?'<div class="actions"><span></span><button class="primary" data-stage-next>السؤال التالي</button></div>':''}${actions(page+1,page===7?'ماذا تعلمنا؟':'المرحلة التالية',!all||(page===6&&!sorted))}`;}
if(page===8)content=`<span class="eyebrow">نربط المعاني معًا</span><h1>ماذا تعلمنا؟</h1><p class="lede">افتحي كل فكرة لتتذكري الآية المرتبطة بها.</p>${disclosures(summaries)}${actions(9,'إلى الاختبار')}`;
if(page===9){if(quizDone){let score=quizFirst.filter(Boolean).length;content=`<section class="panel finish"><span class="eyebrow">ثمرة الرحلة</span><h1>أحسنتِ! اكتملت رحلتك مع آيات سورة الرعد 🌿</h1><div class="score">${ar(score)} / ٥</div><p>إجابات صحيحة من المحاولة الأولى</p><p>النتيجة النهائية: <strong>${ar(score*20)}٪</strong></p><p class="footer-note">أكملتِ الأسئلة الخمسة جميعها بإجابات صحيحة بعد المحاولة والتعلّم.</p><div class="review">${quiz.map((q,i)=>`<p>${quizFirst[i]?'✓':'↻'} السؤال ${ar(i+1)}: ${quizFirst[i]?'صحيح من المحاولة الأولى':'أجبتِ عنه بعد إعادة المحاولة'}</p>`).join('')}</div><div class="actions"><button class="secondary" data-go="8">راجعي الخلاصة</button><button class="primary" data-retry>أعيدي الاختبار</button></div></section>`;}else if(quizAt===-1){content=`<section class="panel finish"><span class="eyebrow">وصلتِ إلى المحطة الأخيرة</span><h1>اكتملت الرحلة</h1><h2>اختبري ما تعلمتِ</h2><p>خمس أسئلة تربط المعاني بمواقف وأفكار تعلمتِها.</p><p class="hint">تُحسب درجتك من المحاولة الأولى لكل سؤال، ويمكنك المحاولة مجددًا حتى تصلي إلى الإجابة الصحيحة.</p><button class="primary" data-start-quiz>ابدأ الاختبار</button></section>${actions(8,'راجعي الخلاصة')}`;}else{content=`<span class="eyebrow">اختبري ما تعلمتِ</span><h1>خطوة أخيرة لترسيخ المعنى</h1><div class="progress"><span style="width:${quizAt*20}%"></span></div>${questionMarkup(quiz[quizAt],quizAt,quizSolved[quizAt],quizWrong[quizAt],true)}<p class="hint">تُحسب النتيجة من المحاولة الأولى. خذي وقتك في التفكير.</p>`;}}
let progress=quizDone?100:Math.round((unlocked-1)/9*100);app.innerHTML=`<div class="shell"><aside class="sidebar"><h2>مسار الرحلة</h2><nav aria-label="مراحل الرحلة">${navNames.map((n,i)=>`<button class="nav-item ${page===i+1?'active':''} ${unlocked>i+1?'done':''}" data-go="${i+1}" ${i+1>unlocked?'disabled':''} ${page===i+1?'aria-current="step"':''}><span class="dot">${unlocked>i+1?'✓':ar(i+1)}</span>${n}</button>`).join('')}</nav><div class="progress"><span style="width:${progress}%"></span></div><span class="progress-label">${ar(progress)}٪ من الرحلة</span></aside><main id="main" tabindex="-1">${content}</main></div>`;if(focus){document.getElementById('main').focus({preventScroll:true});window.scrollTo(0,0);}bindDrag();}
function go(n){if(n>=0&&n<=unlocked){page=n;render();}}
document.addEventListener('click',e=>{let b=e.target.closest('button');if(!b||b.disabled)return;
if(b.hasAttribute('data-go'))go(+b.dataset.go);
if(b.hasAttribute('data-next')){let n=+b.dataset.next;unlocked=Math.max(unlocked,n);page=n;render();}
if(b.hasAttribute('data-word')){let i=+b.dataset.word,[,label,meaning]=vocabulary[i],box=document.getElementById('meaning');let close=b.getAttribute('aria-expanded')==='true';document.querySelectorAll('.word').forEach(w=>w.setAttribute('aria-expanded','false'));box.classList.toggle('show',!close);box.textContent=close?'':`${label}: ${meaning}`;b.setAttribute('aria-expanded',String(!close));}
if(b.hasAttribute('data-answer')){let answer=+b.dataset.answer;if(page===9&&quizAt>=0&&!quizDone){let q=quiz[quizAt];if(quizFirst[quizAt]===null)quizFirst[quizAt]=answer===q.answer;if(answer===q.answer){quizSolved[quizAt]=true;quizWrong[quizAt]=null;}else quizWrong[quizAt]=answer;}else if(page>=3&&page<=7){let state=stageState[page-3],q=stages[page-3].questions[state.at];if(answer===q.answer){state.solved[state.at]=true;state.wrong[state.at]=null;}else state.wrong[state.at]=answer;}render(false);document.querySelector('.feedback:not(:empty)')?.scrollIntoView({block:'nearest'});}
if(b.hasAttribute('data-stage-next')){let s=stageState[page-3];if(s.solved[s.at]&&s.at<stages[page-3].questions.length-1){s.at++;render(false);document.getElementById('question').scrollIntoView({block:'start'});}}
if(b.hasAttribute('data-move')){let [i,delta]=b.dataset.move.split(',').map(Number);moveCard(i,i+delta);}
if(b.hasAttribute('data-check-sort')){sorted=order.every((v,i)=>v===i);sortMessage=sorted?'أحسنتِ! ✨ التوحيد يقود إلى إفراد الله تعالى بالعبادة.':'حاولي مرة أخرى';render(false);}
if(b.hasAttribute('data-start-quiz')){quizAt=0;render();}
if(b.hasAttribute('data-quiz-next')&&quizSolved[quizAt]){if(quizAt===4)quizDone=true;else quizAt++;render();}
if(b.hasAttribute('data-retry')){quizAt=0;quizDone=false;quizSolved=quiz.map(()=>false);quizFirst=quiz.map(()=>null);quizWrong=quiz.map(()=>null);render();}
});
function moveCard(from,to){if(sorted||to<0||to>2||from===to)return;const [c]=order.splice(from,1);order.splice(to,0,c);sortMessage='';render(false);}
function bindDrag(){document.querySelectorAll('[data-sort]').forEach(el=>{el.addEventListener('dragstart',e=>{if(sorted){e.preventDefault();return;}dragIndex=+el.dataset.sort;e.dataTransfer.effectAllowed='move';e.dataTransfer.setData('text/plain',String(dragIndex));});el.addEventListener('dragover',e=>{if(!sorted){e.preventDefault();e.dataTransfer.dropEffect='move';}});el.addEventListener('drop',e=>{e.preventDefault();if(dragIndex!==null)moveCard(dragIndex,+el.dataset.sort);dragIndex=null;});el.addEventListener('dragend',()=>{dragIndex=null;});});}
render();
